### ISSUE TITLE
Доработки для jsonrpc client

### ISSUE THREAD

**Issue by e-konyukov** [tochka-public/Tochka.JsonRpc#12]
- сделать флаг **HasError** для _jsonrpcresult_
- сделать метод **GetAnyError** для _jsonrpcresult_
- метод **_AsError<>_** сейчас падает если в ответе нет поля _data_
Пример - как хотим использовать:
`if (rpcResult.HasError)
            {
                var error = rpcResult.GetAnyError();
                log.LogError(error);
                return null;
            }`

- когда ловим _JsonRpcException_ и делаем _ToString()_, некорректно отображается _Json Rpc Error_, полученный от сервиса, к которому обращались.
Пример:
`JSON Rpc error:
        Tochka.JsonRpc.Common.Models.Response.Errors.Error 1[Newtonsoft.Json.Linq.JToken]`
 Как хотим:
`JSON Rpc error: 
{
     code: some-code,
     message: some-message,
     data: some-data
}`

- когда делаю моки в тестах, не могу сделать что то типа:
`.Throws<JsonRpcException>()`
т.к. **must have a public parameterless constructor**

**Comment by Rast1234** [comment]
+ косяк с парсингом, когда отсутствует Data в ошибке
