### ISSUE TITLE
[OpenRPC] ApiExplorerSettingsAttribute.GroupName is ignored

### ISSUE THREAD

**Issue by RoboBurned** [tochka-public/Tochka.JsonRpc#88]
Setting GroupName with ApiExplorerSettingsAttribute on controller has no effect on OpenRPC result.
JsonRpcDescriptionProvider overrides the value of ApiDescription.GroupName with constant "jsonrpc".

GroupName is used when application has several independed APIs.
Ex:
```cs
[ApiExplorerSettings(GroupName = "admin")]
[ApiController]
[Route("/admin/api")]
AdminApiControllerBase : JsonRpcControllerBase
{
}

[ApiExplorerSettings(GroupName = "user")]
[ApiController]
[Route("/user/api")]
UserApiControllerBase : JsonRpcControllerBase
{
}
```
And in Startup.cs
```cs
services.AddOpenRpc(Assembly.GetExecutingAssembly(), options =>
{
options.Docs.Add("jadmin_v1", new OpenRpcInfo("Admin API", "1"));
options.Docs.Add("user_v1", new OpenRpcInfo("User API", "1"));
});
```
In this case /openrpc/admin_v1.json should return details for Admin API but it returns no methods because JsonRpcDescriptionProvider replaces specified GroupName.

JsonRpcDescriptionProvider should not change GroupName if it was determined by DefaultApiDescriptionProvider

**Comment by OptimumDev** [comment]
Hello! Thank you for the issue. We need a bit of time to search for possible solutions and will try to fix it the best possible way

**Comment by RoboBurned** [comment]
New version works great. Thanks!
